algoritmo "exercicio7"
// Disciplina   : P.A
// Professor   : Cíntia Pinho
// Descrição   : Lê números infinitos, ou até você digitar 0(zero).
// Autor(a)    : Yuri Candido da Silva
// Data atual  : 8/21/2021
var
x, n, soma:inteiro
inicio

repita
para n de n ate n faca
 escreva("Digite um valor: ")
 leia(x)
 soma<-soma+x
fimpara

escreval("Resultado: ",soma)

ate(x=0)
fimalgoritmo