Algoritmo "exercicio10"
// Disciplina   : P.A
// Professor   : Cíntia Pinho
// Descrição   : Fatorial de um número.
// Autor(a)    : Yuri Candido da Silva
// Data atual  : 8/21/2021
Var
num, fat, cont: inteiro

Inicio
repita
fat<- 1
   escreval("  ")
   escreval("Digite um número: ")
   leia(num)

   para cont de num ate 1 passo -1 faca

   fat<- fat*cont
   fimpara
escreval("Fatorial de",num," é:",fat)

ate num=0

Fimalgoritmo