Algoritmo "area_triangulo"



Var

area,base,alt: real

Inicio


//entrada de dados

escreval("----------ESTE PROGRAMA CALCULA A ÁREA DO TRIÂNGULO--------")

escreval("Digite a base do triângulo retângulo")
leia(base)

escreval("Digite a altura do triângulo retângulo")
leia(alt)

//processamento
area <- (base*alt)/2

//saída

escreval("A área do triângulo retângulo é: ", area, "m²")

Fimalgoritmo